Opt("GUIOnEventMode", 1)
#Region ### START Koda GUI section ### Form=e:\program file\auto\autoit\autoit3\gui\forms\tool_autoclick_adiphy.kxf

GUICtrlSetOnEvent($mitemFile, "mitemFileClick")
GUICtrlSetOnEvent($MenuItemHelp, "MenuItemHelpClick")
GUICtrlSetOnEvent($mitemContact, "mitemContactClick")
GUICtrlSetOnEvent($mitemKeyActive, "mitemKeyActiveClick")
GUICtrlSetOnEvent($mitemAbout, "mitemAboutClick")
GUISetOnEvent($GUI_EVENT_CLOSE, "frmMainClose")
GUISetOnEvent($GUI_EVENT_MINIMIZE, "frmMainMinimize")
GUISetOnEvent($GUI_EVENT_MAXIMIZE, "frmMainMaximize")
GUISetOnEvent($GUI_EVENT_RESTORE, "frmMainRestore")
GUICtrlSetOnEvent($cboxLogEnable, "cboxLogEnableClick")
GUICtrlSetOnEvent($cboxLogWrite, "cboxLogWriteClick")
GUICtrlSetOnEvent($lblStartTime, "lblStartTimeClick")
GUICtrlSetOnEvent($lblEndTime, "lblEndTimeClick")
GUICtrlCreateGroup("", -99, -99, 1, 1)
GUICtrlSetData($editSock, "")
GUICtrlSetOnEvent($editSock, "editSockChange")
GUICtrlSetFont($lblExamSock, 11, 400, 0, "Arial Narrow")
GUICtrlSetOnEvent($lblExamSock, "lblExamSockClick")
GUICtrlCreateGroup("", -99, -99, 1, 1)
GUICtrlSetState($editLogResult, $GUI_DISABLE)
GUICtrlSetOnEvent($editLogResult, "editLogResultChange")
GUICtrlCreateGroup("", -99, -99, 1, 1)
GUICtrlSetData($editResult, "")
GUICtrlSetState($editResult, $GUI_DISABLE)
GUICtrlSetOnEvent($editResult, "editResultChange")
GUICtrlCreateGroup("", -99, -99, 1, 1)
GUICtrlSetOnEvent($btnRun, "btnRunClick")
GUICtrlSetOnEvent($btnStop, "btnStopClick")
GUICtrlSetOnEvent($btnUploadSocks, "btnUploadSocksClick")
GUISetState(@SW_SHOW)
#EndRegion ### END Koda GUI section ###